# Generated by Django 6.0.2 on 2026-03-04 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_rename_category_tag_rename_category_posts_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='tag',
            new_name='tags',
        ),
    ]
